language: java
jdk: openjdk8
install: mvn clean install -B -V
cache:
  directories:
    - $HOME/.m2
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_API_KEY
    file_glob: true
    draft: true
    file:
      - "target/*.jar"
    on:
      tags: true

  - provider: bintray
    skip_cleanup: true
    user: $BINTRAY_USER
    key:  $BINTRAY_KEY
    file: 'target/bintray.json'
    on:
      tags: true
